### ISSUE TITLE
开源代码

### ISSUE THREAD

**Issue by yangjiangeyjg** [Xiaoqi-Zhao-DLUT/SSLSOD#1]
你好啊，请问你们什么时候开源代码呢？

**Comment by Xiaoqi-Zhao-DLUT** [comment]
After the AAAI 2022 virtual conference.

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@yangjiangeyjg After the AAAI 2022 virtual conference.

**Comment by yangjiangeyjg** [comment]
> @yangjiangeyjg After the AAAI 2022 virtual conference.
你好啊，请问方便提供一下训练数据的链接嘛
