### ISSUE TITLE
> @yangjiangeyjg After the AAAI 2022 virtual conference.

### ISSUE THREAD

**Issue by yangjiangeyjg** [Xiaoqi-Zhao-DLUT/SSLSOD#2]
> @yangjiangeyjg After the AAAI 2022 virtual conference.
你好啊，请问方便提供一下训练数据的链接嘛

_Originally posted by @yangjiangeyjg in https://github.com/Xiaoqi-Zhao-DLUT/SSLSOD/issues/1#issuecomment-1080614436_

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@yangjiangeyjg  I've updated these links.
